### ISSUE TITLE
Dataset release?

### ISSUE THREAD

**Issue by Spark001** [showlab/DeVRF#2]
How do you get the dynamic scenes? 
e.g. for Lego, did you get the 3D model, then manipulate and render in Blender/Unity ?

Did you have a plan for release the dynamic datasets?

**Comment by Jia-Wei-Liu** [comment]
Yes, to get the synthetic dynamic scenes such as Lego, we render a deforming 3D model in Blender. We have released the DeVRF code and dataset. Please feel free to let me know if you have further questions. Thanks!
Best regards!

**Comment by anona-R** [comment]
Hi,  Thanks for the excellent work. Could you please share the mesh objects for Daisy, plant, and Flower 360?
