### ISSUE TITLE
Forward motion vector

### ISSUE THREAD

**Issue by SilenKZYoung** [showlab/DeVRF#3]
Thank you for your exciting work! I'm curious about the 4D Deformation Cycle Consistency in losses. It's easy to understand the backward motion by constructing the deformation field to map any spatial points in a specific time to the canonical space, but how do you build the inverse mapping (i.e. the forward motion vector)? It will be helpful if you release the source code.

**Comment by Jia-Wei-Liu** [comment]
Thanks for your interest!

The modelling of forward motion vector is similar to the backward motion vector. It is modelled as 4D forward deformation voxels with the same resolution as the backward deformation. The 3D forward motion from canonical 3D points to their corresponding 3D points at time step t can be efficiently queried through quadruple interpolation of their neighboring voxels at neighboring time steps in the 4D forward deformation field, as shown in Eq. (2) of the main paper. The 4D forward deformation field is jointly optimized with the 4D backward deformation field through 4D deformation cycle consistency and optical flow supervision.

We have released the DeVRF code and dataset. Please feel free to let me know if you have further questions. Thanks!
Best regards!
