### ISSUE TITLE
Pre-trained RAFT model

### ISSUE THREAD

**Issue by dsvilarkovic** [showlab/DeVRF#4]
Hello,
Nice work, really like the idea!
In both paper and readme I think it is not explicitly mentioned whether your RAFT model is pre-trained on RAFT's data (and if yes, on which datasets) or on your own?

Regards!

**Comment by Jia-Wei-Liu** [comment]
Hello,

Thanks for your interest!
The RAFT model is pre-trained on RAFT's data. Specifically, we use the pre-trained model on Sintel dataset, which can be downloaded from RAFT github. Hope that clarifies.

Best regards!
