### ISSUE TITLE
how i  reproduce both time and vies sys?

### ISSUE THREAD

**Issue by Alex-Zhu1** [showlab/DeVRF#5]
Thanks your great work!
i meet a problem about render_video.
The commend:  --render_only --render_video, for me , just can fix-time and view-sys.  can't create a Bullet time！
can you give me some advisers?
i dont modify the code

**Comment by Jia-Wei-Liu** [comment]
Hello! Thanks for your interest!

You can create a Bullet time by fixing the time and manually design a 360 camera pose trajectory. In my case, I just rotate the camera pose around an axis, e.g., y-axis, and render novel views at these camera poses. Hope this helps!

Best regards!
