### ISSUE TITLE
Building extension module adam_upd_cuda...

### ISSUE THREAD

**Issue by beibeirory** [showlab/DeVRF#6]
Thanks for your great work. But I got a problem.

No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
/home/llh/.conda/envs/devrf/lib/python3.7/site-packages/mmcv/__init__.py:21: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  'On January 1, 2023, MMCV will release v2.0.0, in which it will remove '
Using /home/llh/.cache/torch_extensions as PyTorch extensions root...
/home/llh/experiments/code/DeVRF-main/static_DirectVoxGO/lib/cuda/adam_upd.cpp -> /home/llh/experiments/code/DeVRF-main/static_DirectVoxGO/lib/hip/adam_upd.cpp skipped
/home/llh/experiments/code/DeVRF-main/static_DirectVoxGO/lib/cuda/adam_upd_kernel.cu -> /home/llh/experiments/code/DeVRF-main/static_DirectVoxGO/lib/hip/adam_upd_kernel.hip skipped
Successfully preprocessed all matching files.
Total number of unsupported CUDA function calls: 0

Total number of replaced kernel launches: 3
Detected CUDA files, patching ldflags
Emitting ninja build file /home/llh/.cache/torch_extensions/adam_upd_cuda/build.ninja...
Building extension module adam_upd_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.11.1.git.kitware.jobserver-1
Loading extension module adam_upd_cuda...
Traceback (most recent call last):
  File "run.py", line 13, in <module>
    from lib import utils, dvgo, dmpigo
  File "/home/llh/experiments/code/DeVRF-main/static_DirectVoxGO/lib/utils.py", line 11, in <module>
    from .masked_adam import MaskedAdam
  File "/home/llh/experiments/code/DeVRF-main/static_DirectVoxGO/lib/masked_adam.py", line 10, in <module>
    verbose=True)
  File "/home/llh/.conda/envs/devrf/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1092, in load
    keep_intermediates=keep_intermediates)
  File "/home/llh/.conda/envs/devrf/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1318, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/llh/.conda/envs/devrf/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1700, in _import_module_from_library

**Comment by Jia-Wei-Liu** [comment]
Hello! Thanks for your kind words!

It seems the adam_upd_cuda is not successfully built. Could you please check your environments settings, such as pytorch, cuda versions? In addition, I find similar questions in https://github.com/sunset1995/DirectVoxGO/issues/24. I suggest maybe you could check whether those discussions are helpful for you?
