### ISSUE TITLE
How to extract the mask in dynamic_4views/train_flow

### ISSUE THREAD

**Issue by yuangan** [showlab/DeVRF#7]
Thank you for your great work~
I'm trying to run your work in my own dataset. And there is a question about the mask used in the optical flow. The RAFT demo does not output any mask of optical flow. And a mask can only be found in the function "upsample_flow", which is used to "balance the gradient" and has a shape of (1, 576, 100, 100). Is this the "mask" used in dynamic_4views/train_flow? If not, could you offer the source code to extract the "mask" used in dynamic_4views/train_flow? 
I'm looking forward to hearing from you.

**Comment by Jia-Wei-Liu** [comment]
Hello! Thanks for your kind words!

The RAFT demo code I used can automatically generate the mask of optical flow. The specific demo code is the same as  DynamicNeRF https://github.com/gaochen315/DynamicNeRF/blob/main/utils/generate_flow.py. You can find the save masks code in line 86-94. Hope that helps.

Feel free to let me know if you have further question.

**Comment by yuangan** [comment]
Thanks, the code helps me a lot.
